sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.113.201.249
    port: 3306
    database: sky_take_out
    username: root
    password: 999426
  redis:
    host: localhost
    port: 6379
    password: 999426
    database: 0